services:
  mongodb:
    image: mongo:7
    container_name: dochub-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: dochub-redis
    ports:
      - "6380:6379"

volumes:
  mongodb_data:
